services:
  postgres:
    build: ./database
    container_name: gymbuddy-db
    environment:
      POSTGRES_DB: gymbuddy_db
      POSTGRES_USER: gymbuddy_user
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gymbuddy-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gymbuddy_user -d gymbuddy_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: gymbuddy-backend
    environment:
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_NAME: gymbuddy_db
      DB_USER: gymbuddy_user
      DB_PASSWORD: root
      PORT: "3001"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3001:3001"
    networks:
      - gymbuddy-network

  frontend:
    build: ./frontend
    container_name: gymbuddy-frontend
    environment:
      NEXT_PUBLIC_API_URL: http://backend:3001
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - gymbuddy-network

volumes:
  postgres_data:

networks:
  gymbuddy-network:
    driver: bridge